/**
 * Generated indexes and the dashboard.
 *
 * Everything here is rebuilt by *reading the vault*, never by calling the API.
 * That is what makes "Rebuild generated indexes" work offline and after a
 * restore, and it means an index can never disagree with the notes it lists.
 *
 * Dataview is not required. The generated tables are plain Markdown.
 */
import { CAPABILITIES } from "../providers/capabilities";
import { FOLDERS, dashboardPath, indexPath, joinPath } from "./paths";
import { SyncSummary } from "../models/domain";
import { VaultIO } from "./vaultIo";
import { escapeLinkText, escapeTableCell } from "./escape";
import { splitDocument } from "./frontmatter";
import { verseSortKey } from "./reference";

/** The subset of frontmatter an index needs. */
export interface IndexEntry {
  path: string;
  id: string;
  reference: string;
  usfm: string;
  color: string;
  bibleVersion: string;
  url: string;
  status: string;
  lastSyncedAt: string;
}

/** Read a top-level scalar out of frontmatter without a YAML dependency. */
export function readField(frontmatter: string, key: string): string | undefined {
  const pattern = new RegExp(`^${key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}:\\s*(.*)$`, "m");
  const match = pattern.exec(frontmatter);
  if (!match) return undefined;
  const raw = (match[1] ?? "").trim();
  if (raw === "") return undefined;
  if ((raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"))) {
    return raw.slice(1, -1).replace(/\\"/g, '"').replace(/\\n/g, "\n").replace(/\\\\/g, "\\");
  }
  return raw;
}

/** Scan the Highlights folder and read each note's managed frontmatter. */
export async function collectHighlightEntries(io: VaultIO, root: string): Promise<IndexEntry[]> {
  const folder = joinPath(root, FOLDERS.highlights);
  const files = await io.listFiles(folder);
  const entries: IndexEntry[] = [];

  for (const path of files) {
    if (!path.endsWith(".md") || path.endsWith(".sync-conflict.md")) continue;
    let content: string;
    try {
      content = await io.read(path);
    } catch {
      continue; // A note that cannot be read is skipped, not fatal.
    }
    const { frontmatter } = splitDocument(content);
    if (!frontmatter) continue;
    if (readField(frontmatter, "source") !== "youversion") continue;

    const id = readField(frontmatter, "youversion_id");
    const usfm = readField(frontmatter, "usfm");
    if (!id || !usfm) continue;

    entries.push({
      path,
      id,
      usfm,
      reference: readField(frontmatter, "reference") ?? usfm,
      color: readField(frontmatter, "color") ?? "",
      bibleVersion:
        readField(frontmatter, "bible_version") ?? readField(frontmatter, "bible_version_id") ?? "",
      url: readField(frontmatter, "youversion_url") ?? "",
      status: readField(frontmatter, "sync_status") ?? "synced",
      lastSyncedAt: readField(frontmatter, "last_synced_at") ?? "",
    });
  }

  entries.sort((a, b) => {
    const bookCmp = a.usfm.localeCompare(b.usfm);
    return bookCmp !== 0 && a.usfm.slice(0, 3) !== b.usfm.slice(0, 3)
      ? a.usfm.slice(0, 3).localeCompare(b.usfm.slice(0, 3))
      : verseSortKey(a.usfm) - verseSortKey(b.usfm);
  });

  return entries;
}

const GENERATED_NOTICE =
  "*This file is generated by YouVersion Sync and is rewritten on every sync. " +
  "Edits here will be lost - write in the individual notes instead.*";

function wikilink(entry: IndexEntry): string {
  // Link by path so the link survives duplicate basenames elsewhere in the vault.
  const target = entry.path.replace(/\.md$/, "");
  return `[[${target}|${escapeLinkText(entry.reference)}]]`;
}

export function renderHighlightIndex(entries: IndexEntry[]): string {
  const lines = [
    "---",
    "source: youversion",
    "youversion_type: index",
    "tags:",
    "  - source/youversion",
    "---",
    "",
    "# Highlights",
    "",
    GENERATED_NOTICE,
    "",
    `${entries.length} highlight${entries.length === 1 ? "" : "s"} imported.`,
    "",
  ];

  if (entries.length === 0) {
    lines.push("No highlights have been imported yet.", "");
    return lines.join("\n");
  }

  lines.push("| Reference | Version | Color | Status | Note |", "| --- | --- | --- | --- | --- |");
  for (const entry of entries) {
    lines.push(
      `| ${escapeTableCell(entry.reference)} | ${escapeTableCell(entry.bibleVersion)} | ` +
        `${escapeTableCell(entry.color)} | ${escapeTableCell(entry.status)} | ${wikilink(entry)} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

/** An index note for a data type YouVersion does not expose. */
export function renderUnavailableIndex(title: string, reason: string): string {
  return [
    "---",
    "source: youversion",
    "youversion_type: index",
    "tags:",
    "  - source/youversion",
    "---",
    "",
    `# ${title}`,
    "",
    GENERATED_NOTICE,
    "",
    `> [!info] Not available`,
    `> ${reason}`,
    "",
  ].join("\n");
}

export interface DashboardContext {
  connected: boolean;
  accountDisplayName: string;
  providerName: string;
  lastSuccessfulSyncAt: string | null;
  lastSummary: SyncSummary | null;
  destinationRoot: string;
  bibleId: number;
  bibleVersion: string;
  /** Human-readable scan scope, e.g. "the whole Bible". */
  scanScope?: string;
  /** True when the scan deliberately skipped part of the Bible. */
  scopeIsPartial?: boolean;
}

export function renderDashboard(entries: IndexEntry[], ctx: DashboardContext): string {
  const conflicts = entries.filter((e) => e.status === "conflict");
  const missing = entries.filter((e) => e.status === "missing_remote");
  const recent = [...entries]
    .sort((a, b) => (b.lastSyncedAt || "").localeCompare(a.lastSyncedAt || ""))
    .slice(0, 10);

  const lines: string[] = [
    "---",
    "source: youversion",
    "youversion_type: dashboard",
    "tags:",
    "  - source/youversion",
    "---",
    "",
    "# YouVersion",
    "",
    GENERATED_NOTICE,
    "",
    "## Status",
    "",
    `- **Connection:** ${ctx.connected ? "Connected" : "Not connected"}${
      ctx.connected && ctx.accountDisplayName ? ` (${ctx.accountDisplayName})` : ""
    }`,
    `- **Source:** ${ctx.providerName}`,
    `- **Bible version:** ${ctx.bibleVersion || ctx.bibleId}`,
    `- **Last successful sync:** ${ctx.lastSuccessfulSyncAt ?? "never"}`,
    `- **Scan scope:** ${ctx.scanScope ?? "unknown"}`,
    "",
  ];

  if (ctx.scopeIsPartial) {
    lines.push(
      "> [!warning] This is a partial view",
      `> Sync only looked at ${ctx.scanScope}. Highlights anywhere else were never requested, so`,
      "> their absence below does not mean you have none. Widen the scan scope in settings.",
      "",
    );
  }

  if (ctx.lastSummary) {
    const s = ctx.lastSummary;
    lines.push(
      "## Last run",
      "",
      `- Chapters scanned: ${s.chaptersScanned} of ${s.chaptersTotal}`,
      `- Created: ${s.created} | Updated: ${s.updated} | Unchanged: ${s.unchanged}`,
      `- Archived or marked missing: ${s.archived} | Conflicts: ${s.conflicted} | Failures: ${s.failed}`,
      `- Finished: ${s.finishedAt ?? "interrupted"}${s.cancelled ? " (cancelled)" : ""}`,
      "",
    );
  }

  lines.push("## Imported", "", `- Highlights: ${entries.length}`, "");

  for (const capability of CAPABILITIES) {
    if (capability.state === "available") continue;
    lines.push(`- ${titleFor(capability.dataType)}: not available`);
  }
  lines.push("");

  if (recent.length > 0) {
    lines.push("## Recently imported highlights", "");
    for (const entry of recent) lines.push(`- ${wikilink(entry)}`);
    lines.push("");
  }

  lines.push(
    "## Reading plans",
    "",
    "Reading plans, plan progress and completed plans cannot be imported.",
    "",
  );

  if (conflicts.length > 0) {
    lines.push("## Conflicts", "");
    for (const entry of conflicts) lines.push(`- ${wikilink(entry)}`);
    lines.push("");
  }

  if (missing.length > 0) {
    lines.push("## No longer in YouVersion", "");
    for (const entry of missing) lines.push(`- ${wikilink(entry)}`);
    lines.push("");
  }

  if (ctx.lastSummary && ctx.lastSummary.errors.length > 0) {
    lines.push("## Errors from the last run", "");
    for (const error of ctx.lastSummary.errors.slice(0, 20))
      lines.push(`- ${escapeTableCell(error)}`);
    lines.push("");
  }

  lines.push(
    "## What the official API does not expose",
    "",
    "YouVersion's public Platform API exposes a single user-data permission, `highlights`.",
    "The following are therefore not imported, and this plugin will not guess at them:",
    "",
  );
  for (const capability of CAPABILITIES) {
    if (capability.state === "available") continue;
    lines.push(`- **${titleFor(capability.dataType)}** - ${capability.reason}`);
  }
  lines.push("");

  return lines.join("\n");
}

function titleFor(dataType: string): string {
  const map: Record<string, string> = {
    note: "Notes",
    bookmark: "Bookmarks and saved verses",
    plan: "Reading plans and progress",
    highlight: "Highlights",
  };
  return map[dataType] ?? dataType;
}

/** Rewrite Dashboard.md and every index note from what is already in the vault. */
export async function rebuildAllIndexes(
  io: VaultIO,
  root: string,
  ctx: DashboardContext,
): Promise<{ highlights: number }> {
  const entries = await collectHighlightEntries(io, root);

  await io.write(indexPath(root, "Highlights"), renderHighlightIndex(entries));

  // Index notes exist for unavailable types too, so the absence is explicit
  // rather than looking like the plugin silently failed.
  for (const capability of CAPABILITIES) {
    if (capability.state === "available") continue;
    const name =
      capability.dataType === "note"
        ? "Notes"
        : capability.dataType === "bookmark"
          ? "Bookmarks"
          : "Plans";
    await io.write(
      indexPath(root, name),
      renderUnavailableIndex(titleFor(capability.dataType), capability.reason),
    );
  }

  await io.write(dashboardPath(root), renderDashboard(entries, ctx));
  return { highlights: entries.length };
}
